const MIS_PROPIEDADES = [
    {
        id: 1,
        type: "sale",
        propertyType: "Casa",
        location: "Valle de Angeles",
        bedrooms: 3,
        bathrooms: 3,
        area: 545,
        price: 5200000,
        priceTag: "L. 5,200,000",
        badge: "En Venta",
        title: "Casa en Las 3 Rosas",
        fullLocation: "📍 Valle de Ángeles, Francisco Morazán",
        images: ["img/imagen1-1.jpg", "img/imagen1-2.jpg", "img/imagen1-3.jpg", "img/imagen1-4.jpg", "img/imagen1-5.jpg"],
        url: "propiedad-1.html"
    },
    {
        id: 2,
        type: "rent",
        propertyType: "Apartamento",
        location: "Tegucigalpa",
        bedrooms: 1,
        bathrooms: 1,
        area: 60,
        price: 18500, // Aproximado a Lempiras por consistencia en filtro
        priceTag: "$ 700/mes",
        badge: "Alquiler",
        title: "Apartamento Exclusivo",
        fullLocation: "📍 Col Tepeyac, Tegucigalpa",
        images: ["img/imagen2-1.jpeg", "img/imagen2-2.jpeg", "img/imagen2-3.jpeg", "img/imagen2-4.jpeg", "img/imagen2-5.jpeg", "img/imagen2-6.jpeg", "img/imagen2-7.jpeg", "img/imagen2-8.jpeg"],
        url: "propiedad-2.html"
    },
    {
        id: 3,
        type: "rent",
        propertyType: "Apartamento",
        location: "Tegucigalpa",
        bedrooms: 1,
        bathrooms: 1,
        area: 50,
        price: 18500,
        priceTag: "$ 700/mes",
        badge: "Alquiler",
        title: "Apartamento en Cipreses",
        fullLocation: "📍 San Ignacio, Tegucigalpa",
        images: ["img/imagen3.jpg"],
        url: "propiedad-3.html"
    },
    {
        id: 4,
        type: "rent",
        propertyType: "Casa",
        location: "Valle de Angeles",
        bedrooms: 3,
        bathrooms: 3,
        area: 545,
        price: 22000,
        priceTag: "L. 22,000",
        badge: "Alquiler",
        title: "Casa en Las 3 Rosas",
        fullLocation: "📍 Valle de Ángeles, Francisco Morazán",
        images: ["img/imagen4-1.jpeg", "img/imagen4-2.jpeg", "img/imagen4-3.jpeg", "img/imagen4-4.jpeg", "img/imagen4-5.jpeg", "img/imagen4-6.jpeg", "img/imagen4-7.jpeg", "img/imagen4-8.jpeg", "img/imagen4-9.jpeg", "img/imagen4-10.jpeg"],
        url: "propiedad-4.html",
        extraFeatures: ["📐 600 m²", "🏗️ Plano", "🔒 Privado"]
    },
    {
        id: 5,
        type: "sale",
        propertyType: "Casa",
        location: "Valle de Angeles",
        bedrooms: 3,
        bathrooms: 3,
        area: 542,
        price: 3500000,
        priceTag: "L. 3,500,000",
        badge: "En Venta",
        title: "Casa en Valle de Ángeles",
        fullLocation: "📍 Valle de Ángeles, Francisco Morazán",
        images: ["img/imagen5-1.jpeg", "img/imagen5-2.jpeg", "img/imagen5-3.jpeg", "img/imagen5-4.jpeg", "img/imagen5-5.jpeg", "img/imagen5-6.jpeg", "img/imagen5-7.jpeg", "img/imagen5-8.jpeg", "img/imagen5-9.jpeg", "img/imagen5-10.jpeg"],
        url: "propiedad-5.html",
        extraFeatures: ["📐 542 m²", "🚗 5 Estac.", "💼 Estudio"]
    },
    {
        id: 6,
        type: "sale",
        propertyType: "Terreno",
        location: "Concepcion",
        area: 255,
        price: 200000,
        priceTag: "L. 200,000",
        badge: "En Venta",
        title: "Terreno a 15 minutos del aeropuerto Tocontin",
        fullLocation: "📍 Concepcion, Tegucigalpa",
        images: ["img/imagen6-1.jpeg"],
        url: "propiedad-6.html"
    },
        {
        id: 7,
        type: "sale",
        propertyType: "Casa",
        location: "Tegucigalpa",
        bedrooms: 7,
        bathrooms: 4,
        area: 250,
        price: 5000000,
        priceTag: "L. 5,000,000",
        badge: "En Venta",
        title: "Casa Vehicular en Col. Kennedy",
        fullLocation: "📍 Tegucigalpa, Francisco Morazán",
        images: ["img/imagen7-1.jpg", "img/imagen7-2.jpg", "img/imagen7-3.jpg", "img/imagen7-4.jpg", "img/imagen7-5.jpg"],
        url: "propiedad-7.html"
    }
];